import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'; 

const sidebars: SidebarsConfig = {
  parcoursSidebar: [{ type: 'autogenerated', dirName: 'parcours-universitaire' }],
  enseignementSidebar: [{ type: 'autogenerated', dirName: 'enseignements' }],
  
  coursSidebar: [
    {
      type: 'category',
      label: 'Big Data',
      items: [
        'cours/BigData/intro',
        'cours/BigData/cm',
        'cours/BigData/td',
        'cours/BigData/tp',
      ],
    },
    {
      type: 'category',
      label: 'BD NoSQL',
      items: [
        'cours/BD_NoSQL/intro',
        'cours/BD_NoSQL/cm',
        'cours/BD_NoSQL/td',
        'cours/BD_NoSQL/tp',
      ],
    },
    {
      type: 'category',
      label: 'BD4',
      items: [
        'cours/BD4/intro',
        'cours/BD4/cm',
        'cours/BD4/td',
        'cours/BD4/tp',
      ],
    },
    {
      type: 'category',
      label: 'DATA5',
      items: [
        'cours/DATA5/intro',
        'cours/DATA5/cm',
        'cours/DATA5/td',
        'cours/DATA5/tp',
      ],
    },
    {
      type: 'category',
      label: 'BD2',
      items: [
        'cours/BD2/intro',
        'cours/BD2/cm',
        'cours/BD2/td',
        'cours/BD2/tp',
      ],
    },
  ],
};

export default sidebars;
